<?php

function hello_theme(){
    return array(
      'hello_theme' =>array(
        'variables' => array(
          'data' => 'data',
          'base_url' => 'base_url',
          'menu' => 'menu',
        ),
      ),

      's_news_theme' =>array(
        'variables' => array(
          'menu' => 'menu',
          'base_url' => 'base_url',
          'news' => 'news',
        ),
      ),
    );
}
